import Testing
import Foundation
import MLX
@testable import RIFEMLX

/// Elementwise parity vs the Python rife-mlx reference (itself parity-locked vs PyTorch).
/// Requires the staged metallib — run via `xcodebuild test`. Fixture + weights paths are
/// environment-specific (generated by /tmp/gen_rife_fixtures.py); tests skip when absent.
struct RIFEParityTests {
    static let fixtureURL = URL(fileURLWithPath: "/tmp/rife_parity.safetensors")
    static let weightsURL = URL(fileURLWithPath:
        "/Users/dustinnielson/.cache/huggingface/hub/models--mlx-community--RIFE-4.25/snapshots/6b650eaa5664aab280119511fe944861491aa15e/model.safetensors")

    @Test func fullInferenceMatchesPythonReference() throws {
        try #require(FileManager.default.fileExists(atPath: Self.fixtureURL.path))
        try #require(FileManager.default.fileExists(atPath: Self.weightsURL.path))

        let fixtures = try MLX.loadArrays(url: Self.fixtureURL)
        let model = RIFEModel()
        try model.loadWeights(from: Self.weightsURL)

        let out = model.inference(img0: fixtures["img0"]!, img1: fixtures["img1"]!,
                                  timestep: 0.5, scale: 1.0)
        MLX.eval(out)

        let expected = fixtures["expected"]!.asType(.float32)
        let got = out.asType(.float32)
        #expect(got.shape == expected.shape)

        let maxAbs = MLX.abs(got - expected).max().item(Float.self)
        let dot = MLX.sum(got * expected).item(Float.self)
        let n1 = MLX.sum(got * got).item(Float.self).squareRoot()
        let n2 = MLX.sum(expected * expected).item(Float.self).squareRoot()
        let cosine = dot / max(n1 * n2, 1e-12)
        print("[RIFE-PARITY] cosine=\(cosine) max_abs=\(maxAbs)")

        // fp32 end-to-end: the skill's full-pass threshold is < 1e-2; fp32 should be far tighter.
        #expect(maxAbs < 1e-2)
        #expect(cosine > 0.9999)
    }
}
